const {_electron:electron}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),artifacts=path.join(root,'artifacts');fs.mkdirSync(artifacts,{recursive:true});
const data=fs.mkdtempSync(path.join(artifacts,'smoke-data-'));
let app;const requests=[];
const launchOptions=()=>({args:process.env.MODELPULSE_EXECUTABLE?['--disable-gpu','--smoke-test']:['--disable-gpu',root,'--smoke-test'],...(process.env.MODELPULSE_EXECUTABLE?{executablePath:process.env.MODELPULSE_EXECUTABLE}:{}),timeout:60000});
const server=http.createServer(async(req,res)=>{
  let body='';for await(const c of req)body+=c;const json=JSON.parse(body);requests.push({url:req.url,body:json,key:req.headers.authorization||req.headers['x-api-key']});
  res.writeHead(200,{'Content-Type':'text/event-stream'});const send=event=>res.write('data: '+JSON.stringify(event)+'\n\n');
  if(req.url.endsWith('/chat/completions')){send({choices:[{delta:{content:'1 2 3 '}}]});await new Promise(r=>setTimeout(r,60));send({choices:[{delta:{content:'4 5 6'},finish_reason:'stop'}]});send({usage:{completion_tokens:12},choices:[]});res.end('data: [DONE]\n\n');}
  else if(req.url.endsWith('/responses')){send({type:'response.output_text.delta',delta:'1 2 3'});await new Promise(r=>setTimeout(r,60));send({type:'response.completed',response:{usage:{output_tokens:8}}});res.end();}
  else{send({type:'message_start',message:{usage:{output_tokens:1}}});send({type:'content_block_delta',delta:{type:'text_delta',text:'1 2 3'}});await new Promise(r=>setTimeout(r,60));send({type:'message_delta',usage:{output_tokens:8},delta:{stop_reason:'end_turn'}});send({type:'message_stop'});res.end();}
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{
  const env={...process.env,MODELPULSE_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;
  app=await electron.launch({...launchOptions(),env});
  const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.waitForFunction(()=>document.getElementById('version')?.textContent==='v0.1.1'&&window.pulse);
  assert.equal(await page.locator('#modelCount').textContent(),'0');
  const geometry=await app.evaluate(({BrowserWindow,screen,nativeTheme})=>({bounds:BrowserWindow.getAllWindows()[0].getBounds(),area:screen.getPrimaryDisplay().workAreaSize,dark:nativeTheme.shouldUseDarkColors}));
  assert.ok(Math.abs(geometry.bounds.width-Math.min(1280,Math.round(geometry.area.width*.4)))<=2);assert.ok(Math.abs(geometry.bounds.height/geometry.bounds.width-.618)<.01);assert.equal(geometry.dark,true);
  assert.equal(await page.locator('.schedule').count(),0);assert.equal(await page.locator('.windowbar #scheduleOpen').count(),1);
  for(const [protocol,name] of [['chat','Chat 测试模型'],['responses','Responses 测试模型'],['anthropic','Anthropic 测试模型']]){
    const windowPromise=app.waitForEvent('window');await page.locator('#addModel').click();const editor=await windowPromise;
    editor.on('pageerror',e=>errors.push(e.message));await editor.waitForSelector('#modelForm');await editor.locator(`[data-protocol="${protocol}"]`).click();await editor.locator('#name').fill(name);await editor.locator('#modelId').fill('fixture-model');await editor.locator('#host').fill(`http://127.0.0.1:${server.address().port}/v1`);await editor.locator('#apiKey').fill('fixture-secret-do-not-leak');
    if(protocol==='chat'&&!process.env.MODELPULSE_EXECUTABLE)await editor.screenshot({path:path.join(artifacts,'editor.png')});
    const closePromise=editor.waitForEvent('close');await editor.locator('button[value="test"]').click();
    let timeout;try{await Promise.race([closePromise,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('Editor did not close after save')),15000);})]);}finally{clearTimeout(timeout);}
    await page.waitForFunction(async()=>{const s=await window.pulse.snapshot();return !s.busy&&s.latest.length===s.models.length;});
  }
  let s=await page.evaluate(()=>window.pulse.snapshot());assert.equal(s.models.length,3);assert.ok(s.latest.every(r=>r.status==='success'&&!r.estimated));assert.equal(requests.length,3);assert.ok(requests.every(r=>r.key?.includes('fixture-secret')));assert.ok(!JSON.stringify(s).includes('fixture-secret'));
  const layout=await page.locator('#cards').evaluate(el=>({width:innerWidth,columns:getComputedStyle(el).gridTemplateColumns.split(' ').length}));if(layout.width>500&&layout.width<1080)assert.equal(layout.columns,2);
  if(!process.env.MODELPULSE_EXECUTABLE)await page.screenshot({path:path.join(artifacts,'models.png')});
  const sticky=await page.evaluate(()=>{document.querySelector('#cards').style.paddingBottom='1200px';scrollTo(0,800);const bar=document.querySelector('.windowbar').getBoundingClientRect(),tabs=document.querySelector('.tabs').getBoundingClientRect();return {barTop:bar.top,tabsTop:tabs.top};});assert.ok(sticky.barTop>=31&&sticky.barTop<34);assert.ok(sticky.tabsTop>=80&&sticky.tabsTop<88);await page.evaluate(()=>{scrollTo(0,0);document.querySelector('#cards').style.paddingBottom='';});
  await page.locator('[data-view="history"]').click();await page.waitForSelector('#chart canvas');if(!process.env.MODELPULSE_EXECUTABLE)await page.screenshot({path:path.join(artifacts,'history.png')});assert.equal(await page.locator('.history-row').count(),3);
  const firstModelId=s.models[0].id;await page.evaluate(id=>echarts.getInstanceByDom(document.querySelector('#chart')).dispatchAction({type:'legendToggleSelect',name:id}),firstModelId);assert.ok(await page.locator(`.history-row[data-model-id="${firstModelId}"]`).count()===0);
  await page.evaluate(()=>echarts.getInstanceByDom(document.querySelector('#chart')).dispatchAction({type:'dataZoom',start:20,end:80}));await page.locator('#historyMetric').selectOption('ttftMs');const zoom=await page.evaluate(()=>echarts.getInstanceByDom(document.querySelector('#chart')).getOption().dataZoom[0]);assert.equal(Math.round(zoom.start),20);assert.equal(Math.round(zoom.end),80);
  await page.locator('[data-view="models"]').click();const schedulePromise=app.waitForEvent('window');await page.locator('#scheduleOpen').click();const scheduleWindow=await schedulePromise;await scheduleWindow.waitForSelector('#nextRuns li');assert.equal(await scheduleWindow.locator('#nextRuns li').count(),5);const countBefore=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length);await page.locator('#scheduleOpen').click();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),countBefore);
  const settingsPromise=app.waitForEvent('window');await page.locator('#settingsOpen').click();const settingsWindow=await settingsPromise;await settingsWindow.waitForSelector('#settingsForm');assert.equal(await settingsWindow.locator('#threshold, #confirmations').count(),0);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),3);await settingsWindow.locator('#maxTokens').fill('1025');await settingsWindow.waitForTimeout(100);await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:0});});await settingsWindow.locator('#cancel').click();await settingsWindow.waitForTimeout(100);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().length),3);await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1});});const settingsClose=settingsWindow.waitForEvent('close');await settingsWindow.locator('#cancel').click();await settingsClose;
  await scheduleWindow.locator('#frequency').selectOption('week');await scheduleWindow.locator('#hour').fill('10');await scheduleWindow.locator('#minute').fill('30');await scheduleWindow.locator('#week').selectOption('5');const scheduleClose=scheduleWindow.waitForEvent('close');await scheduleWindow.locator('#scheduleForm button[type="submit"]').click();await scheduleClose;s=await page.evaluate(()=>window.pulse.snapshot());assert.equal(s.settings.cron,'30 10 * * 5');assert.equal(s.settings.scheduleEnabled,false);
  const toggle=page.locator('[data-toggle]').first();await toggle.uncheck();await page.waitForFunction(async()=>{const s=await window.pulse.snapshot();return s.models.filter(m=>!m.enabled).length===1;});
  const windowPromise=app.waitForEvent('window');await page.locator('[data-edit]').first().click();const editor=await windowPromise;await editor.waitForSelector('#name');assert.equal(await editor.locator('#apiKey').inputValue(),'');await editor.locator('#name').fill('已编辑的模型');const closing=editor.waitForEvent('close');await editor.locator('button[value="save"]').click();await closing;
  if(process.env.MODELPULSE_EXECUTABLE){
    await page.evaluate(async()=>{const s=await window.pulse.snapshot();await window.pulse.saveSettings({...s.settings,cron:'* * * * *',scheduleEnabled:true});});
    console.log('Waiting for one real Cron tick against local fixtures (at most 60 seconds)...');
    await page.waitForFunction(async()=>{const s=await window.pulse.snapshot();return !s.busy&&s.latest.filter(r=>r.source==='scheduled').length===2;},{},{timeout:75000});
    const scheduled=await page.evaluate(()=>window.pulse.snapshot());assert.equal(scheduled.notifications.length,0);
    await page.evaluate(async()=>{const s=await window.pulse.snapshot();await window.pulse.saveSettings({...s.settings,cron:'30 10 * * 5',scheduleEnabled:false});});
  }
  assert.ok(!fs.readFileSync(path.join(data,'model-pulse.sqlite')).includes(Buffer.from('fixture-secret-do-not-leak')));
  assert.deepEqual(errors,[]);await app.close();app=null;
  const {Store}=require('../src/core/store.cjs');const seeded=await Store.open(data);const sample=seeded.latest()[0];
  for(let i=0;i<65;i++)seeded.addResult({...sample,timestamp:new Date(Date.now()-(i+1)*60000).toISOString(),tokensPerSecond:50+20*Math.sin(i/4)},'history-fixture');seeded.addNotification({type:'error',title:'自测通知',body:'用于验证全量清空'});
  seeded.close();
  app=await electron.launch({...launchOptions(),env});const restarted=await app.firstWindow();await restarted.waitForFunction(async()=>window.pulse&&(await window.pulse.snapshot()).models.length===3);const persisted=await restarted.evaluate(()=>window.pulse.snapshot());assert.equal(persisted.latest.length,3);assert.equal(persisted.settings.cron,'30 10 * * 5');assert.ok(persisted.models.some(m=>m.name==='已编辑的模型'));
  await restarted.locator('[data-view="history"]').click();await restarted.waitForFunction(()=>document.querySelectorAll('.history-row').length===50);assert.equal(await restarted.locator('#historyRecords').evaluate(d=>d.open),false);assert.ok(await restarted.locator('#chart canvas').count());assert.equal(await restarted.evaluate(()=>echarts.getInstanceByDom(document.querySelector('#chart')).getOption().dataZoom.length),2);
  if(!process.env.MODELPULSE_EXECUTABLE)await restarted.screenshot({path:path.join(artifacts,'history.png')});
  await restarted.locator('[data-view="notifications"]').click();assert.equal(await restarted.locator('.notification').count(),1);await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:0});});await restarted.locator('#clearNotifications').click();assert.equal((await restarted.evaluate(()=>window.pulse.snapshot())).notifications.length,1);await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1});});await restarted.locator('#clearNotifications').click();await restarted.waitForFunction(async()=>(await window.pulse.snapshot()).notifications.length===0);
  await restarted.locator('[data-view="history"]').click();await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:0});});await restarted.locator('#clearHistory').click();assert.ok((await restarted.evaluate(()=>window.pulse.history({days:7}))).length>50);
  await app.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1});});await restarted.locator('#clearHistory').click();await restarted.waitForFunction(async()=>(await window.pulse.snapshot()).latest.length===0);const cleared=await restarted.evaluate(()=>window.pulse.snapshot());assert.equal(cleared.models.length,3);assert.ok(cleared.models.every(m=>m.hasSecret));assert.equal(cleared.stats.total,0);
  console.log('Desktop smoke passed: window ratio/dark theme, adaptive columns, independent editor, 3 protocols, smooth chart, 50 collapsed records, cancel/confirm clear, credentials preserved, restart persistence.');
}finally{if(app)await app.close();server.close();}})().catch(err=>{console.error(err);process.exitCode=1;});
