import {$,esc,labels,format,date,toast,act} from './shared.js';
import {drawChart} from './chart.js';
document.body.classList.toggle('windows',window.pulse.platform==='win32');
let state,filter='all',view='models',refreshing=false,refreshAgain=false,historyGeneration=0,historyData=[],historyVisibility={},historyZoom={start:0,end:100};
async function refresh(){if(refreshing){refreshAgain=true;return;}refreshing=true;try{state=await window.pulse.snapshot();render();if(view==='history')await loadHistory();}catch(err){toast(err.message);}finally{refreshing=false;if(refreshAgain){refreshAgain=false;refresh();}}}
function render(){const {models,settings,latest,busy}=state,overview=state.overview||{},summaries=state.summaries||{};const latestById=new Map(latest.map(r=>[r.modelId,r]));
  $('modelCount').textContent=models.length;$('enabledCount').textContent=models.filter(m=>m.enabled).length;
  $('healthyCount').textContent=`${overview.healthyModels||0}/${models.length}`;$('lastRunSuccess').textContent=overview.lastRun?.total?format(overview.lastRun.success/overview.lastRun.total*100)+'%':'—';$('p50Ttft').innerHTML=`${format(overview.p50Ttft,0)} <small>ms</small>`;$('p50Generation').innerHTML=`${format(overview.p50GenerationTokensPerSecond)} <small>t/s</small>`;$('incidentCount').textContent=overview.incidents24h||0;$('nextRun').textContent=state.nextRun?date(state.nextRun):'未开启';
  $('scheduleOpen').title=settings.scheduleEnabled?`已开启 · ${settings.cron} · 下次 ${date(state.nextRun)}`:'定时测试未开启';
  $('testAll').textContent=busy?'■ 停止本轮':'▷ 快速测试';$('testAll').disabled=!models.length;$('benchmarkAll').disabled=!!busy||!models.length;
  $('progress').classList.toggle('hidden',!busy);if(busy)$('progress').textContent=`${busy.mode==='standard'?(busy.warmup?'标准基准 · 预热':'标准基准 · 第 '+busy.round+'/3 轮'):busy.source==='scheduled'?'定时监控':'快速测试'} ${busy.done}/${busy.total} · ${models.find(m=>m.id===busy.current)?.name||'准备中'}…`;
  const q=$('search').value.trim().toLowerCase();const sorted=[...models].sort((a,b)=>(summaries[b.id]?.generation?.p50??-1)-(summaries[a.id]?.generation?.p50??-1));
  const visible=sorted.filter(m=>(filter==='all'||m.protocol===filter)&&(m.name+' '+m.modelId).toLowerCase().includes(q));
  $('cards').innerHTML=visible.map(m=>{const r=latestById.get(m.id),summary=summaries[m.id]||{},status=r?.status||'idle',running=busy?.current===m.id,success=status==='success'&&!r.stale,rank=summary.generation?.eligible>=3?sorted.filter(x=>summaries[x.id]?.generation?.eligible>=3).findIndex(x=>x.id===m.id)+1:null;const healthLabels={healthy:'正常',degraded:'性能下降',unavailable:'不可用',insufficient:'数据不足'},stabilityLabels={stable:'稳定',moderate:'一般',volatile:'波动较大',insufficient:'数据不足'};
    return `<article class="card"><div class="card-head"><div class="model-title"><span class="rank">${rank?'#'+rank:'—'}</span>${esc(m.name)}</div><div class="actions"><span class="health health-${summary.health||'insufficient'}">${healthLabels[summary.health]||'数据不足'}</span><span class="tag">${labels[m.protocol]}</span></div></div><div class="endpoint">${esc(m.modelId)} · ${esc(m.host)}</div><div class="cardstats"><div><div class="speed">${format(summary.generation?.p50)} <span class="unit">tokens/s</span></div><div class="stat-label">P50 生成吞吐</div></div><div><div class="number">${format(summary.ttft?.p50,0)} <span class="unit">ms</span></div><div class="stat-label">P50 首字延迟</div></div><div><div class="number">${format(summary.successRate,0)} <span class="unit">%</span></div><div class="stat-label">近 5 次成功率</div></div></div><div class="unit status-${status}">${running?'正在测试…':r?.stale?'配置已变更，请重新测试':r?`${success?'● 成功':status==='cancelled'?'○ 已取消':'● 失败'} · ${esc(date(r.timestamp))}${r.error?' · '+esc(r.error):''}`:'○ 尚未测试'}${summary.generation?` · ${summary.sampleCount||0} 个样本 · ${stabilityLabels[summary.generation.stability]||'数据不足'}${summary.deltaPercent==null?'':` · 较前窗 ${summary.deltaPercent>=0?'+':''}${format(summary.deltaPercent)}%`}`:''}${r?.validation==='invalid'?' · 输出无效':r?.validation==='unchecked'?' · 未校验':''}</div><div class="cardfoot"><label class="toggle"><input type="checkbox" data-toggle="${esc(m.id)}" ${m.enabled?'checked':''} ${busy?'disabled':''}>定时参与</label><div class="actions"><button data-test="${esc(m.id)}" ${busy?'disabled':''}>▷ 快速</button><button data-benchmark="${esc(m.id)}" ${busy?'disabled':''}>◫ 标准</button><button data-edit="${esc(m.id)}" ${busy?'disabled':''}>编辑</button><button data-delete="${esc(m.id)}" ${busy?'disabled':''}>删除</button></div></div></article>`;
  }).join('')||`<div class="empty">${models.length?'没有匹配的模型':'还没有连接模型'}<p>${models.length?'调整搜索词或协议筛选。':'添加远程 API，即可手动测试或加入定时计划。'}</p>${models.length?'':'<button class="primary" id="emptyAdd">＋ 添加第一个模型</button>'}</div>`;
  if($('emptyAdd'))$('emptyAdd').onclick=()=>act(()=>window.pulse.openEditor());
  const unread=state.notifications.filter(n=>!n.read).length;$('notificationTab').textContent='通知'+(unread?` (${unread})`:'');
  $('notificationRows').innerHTML=state.notifications.map(n=>`<article class="notification ${n.read?'':'unread'}"><h2>${esc(n.title)}</h2><p>${esc(n.body)}</p><p class="note">${esc(date(n.timestamp))}</p></article>`).join('')||'<div class="empty section">尚无通知记录<p>排名变化或定时测试异常会在这里记录。</p></div>';
  $('clearNotifications').disabled=!state.notifications.length;$('version').textContent='v'+state.version;
  const selected=$('historyModel').value;
  const ids=new Map(models.map(m=>[m.id,m.name]));for(const r of latest)if(!ids.has(r.modelId))ids.set(r.modelId,r.modelName+'（已删除）');
  $('historyModel').innerHTML='<option value="">全部模型</option>'+[...ids].map(([id,name])=>`<option value="${esc(id)}">${esc(name)}</option>`).join('');if(ids.has(selected))$('historyModel').value=selected;
}
function switchView(value){const enteringHistory=value==='history'&&view!=='history';view=value;for(const key of ['models','history','notifications'])$(key+'View').classList.toggle('hidden',value!==key);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===value));if(value==='history')act(()=>loadHistory({reset:enteringHistory}));}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));if(state)render();});
$('search').oninput=()=>state&&render();$('addModel').onclick=()=>act(()=>window.pulse.openEditor());
$('testAll').onclick=()=>act(()=>state.busy?window.pulse.stopTests():window.pulse.runTests(state.models.map(m=>m.id),'quick'));
$('benchmarkAll').onclick=()=>act(()=>window.pulse.runTests(state.models.map(m=>m.id),'standard'));
$('cards').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.test)act(()=>window.pulse.runTests([b.dataset.test],'quick'));if(b.dataset.benchmark)act(()=>window.pulse.runTests([b.dataset.benchmark],'standard'));if(b.dataset.edit)act(()=>window.pulse.openEditor(b.dataset.edit));if(b.dataset.delete)act(()=>window.pulse.deleteModel(b.dataset.delete));};
$('cards').onchange=e=>{if(e.target.dataset.toggle)act(async()=>{try{await window.pulse.toggleModel(e.target.dataset.toggle,e.target.checked);}finally{await refresh();}});};
$('settingsOpen').onclick=()=>act(()=>window.pulse.openPreferences('settings'));
$('scheduleOpen').onclick=()=>act(()=>window.pulse.openPreferences('schedule'));
function renderHistoryRows(){const rows=historyData.filter(r=>historyVisibility[r.modelId]!==false).slice(0,50),modeLabels={quick:'快速测试',standard:'标准基准',scheduled:'定时监控'};$('historyRows').innerHTML=rows.map(r=>`<div class="history-row" data-model-id="${esc(r.modelId)}"><div><b>${esc(r.modelName)}</b><p>${esc(date(r.timestamp))} · ${modeLabels[r.mode]||(r.source==='scheduled'?'定时监控':'兼容记录')}${r.round?` · 第 ${r.round} 轮`:''}</p><details class="history-detail"><summary>样本诊断</summary><p>验证：${r.validation==='valid'?'有效':r.validation==='invalid'?'输出无效':r.validation==='unchecked'?'未校验':'旧记录'} · 用量：${r.usageSource==='provider'?'供应商返回':r.estimated?'字符估算':'未知'}${r.errorCategory?` · 错误：${esc(r.errorCategory)}`:''}<br>输出 ${r.outputTokens??'—'} tokens / ${r.outputCharacters??'—'} 字符 · 生成阶段 ${format(r.generationMs,0)} ms · 总计 ${format(r.totalMs,0)} ms</p></details></div><div class="record-values"><b class="status-${r.status}">${r.status==='success'?format(r.generationTokensPerSecond)+' t/s':r.status==='cancelled'?'已取消':'失败'}</b><p>${r.status==='success'?`首字 ${format(r.ttftMs,0)} ms · 字符 ${format(r.charactersPerSecond)} /s`:esc(r.error)}</p></div></div>`).join('')||'<p class="empty">当前筛选范围内没有测试记录。</p>';}
function renderHistoryChart(){drawChart(historyData,$('historyMetric').value,{selected:historyVisibility,zoom:historyZoom,onSelectionChange:selected=>{historyVisibility=selected;$('chartEmpty').classList.toggle('hidden',Object.values(selected).some(Boolean));renderHistoryRows();},onZoomChange:zoom=>{historyZoom=zoom;}});$('chartEmpty').classList.toggle('hidden',!Object.keys(historyVisibility).length||Object.values(historyVisibility).some(Boolean));}
function historyQuery(){return {modelId:$('historyModel').value,days:Number($('historyDays').value),mode:$('historyMode').value,status:$('historyStatus').value,errorCategory:$('historyError').value};}
async function loadHistory({reset=false}={}){const gen=++historyGeneration,rows=await window.pulse.history(historyQuery());if(gen!==historyGeneration)return;historyData=rows;if(reset){historyZoom={start:0,end:100};historyVisibility={};}for(const r of rows)if(!(r.modelId in historyVisibility))historyVisibility[r.modelId]=true;renderHistoryChart();renderHistoryRows();}
for(const key of ['historyModel','historyDays','historyMode','historyStatus','historyError'])$(key).onchange=()=>act(()=>loadHistory({reset:true}));$('historyMetric').onchange=renderHistoryChart;
$('exportCsv').onclick=()=>act(async()=>{if(await window.pulse.exportHistory(historyQuery(),'csv'))toast('测试历史已导出为 CSV');});$('exportJson').onclick=()=>act(async()=>{if(await window.pulse.exportHistory(historyQuery(),'json'))toast('测试历史已导出为 JSON');});
$('clearHistory').onclick=()=>act(async()=>{if(await window.pulse.clearHistory()){await refresh();toast('全部测试历史已清空，排名基准已重置');}});
$('clearNotifications').onclick=()=>act(async()=>{if(await window.pulse.clearNotifications()){await refresh();toast('全部通知已清空');}});window.pulse.onChanged(refresh);window.pulse.onNavigate(switchView);window.pulse.onToast(toast);refresh();
